server:
  port: 8080
---

kafka:
  bootstrapServers: localhost:9092

---

api:
  url:
#    product: http://localhost:8080
product: http://product:8080
---

spring:
  profiles: default
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
  datasource:
#    url: jdbc:mysql://database-1.csvj9ae9rzmk.ap-northeast-2.rds.amazonaws.com:3306/ezins
    url: jdbc:mysql://localhost:3306/ezins
    username: sklina
    password: 123456
    driverClassName: org.mariadb.jdbc.Driver
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
#          brokers: 54.180.71.26:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: plan
          destination: ezinsurance
          contentType: application/json
        event-out:
          destination: ezinsurance
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
server:
  port: 8083

---

mybatis:
  mapper-locations: /mapper/**/*.xml